---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  tags:
    - system
    - update

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - software-properties-common
    - python3-pip
