---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  tags:
    - system
    - update

- name: Install required system packages
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - git
      - python3-pip
      - software-properties-common
  tags:
    - system
    - dependencies
