---
- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  tags:
    - docker
    - setup

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  tags:
    - docker
    - setup

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  become: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags:
    - docker
    - setup

- name: Install Docker python module
  pip:
    name: docker
    state: present
  become: true
  tags:
    - docker
    - setup

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  tags:
    - docker
    - permissions

- name: Create Docker network
  docker_network:
    name: "{{ docker_network_name }}"
    state: present
  tags:
    - docker
    - network
