---
- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  tags:
    - docker
    - setup

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  tags:
    - docker
    - setup

- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  tags:
    - docker
    - setup

- name: Create Docker group
  group:
    name: docker
    state: present
  become: true
  tags:
    - docker
    - permissions

- name: Add user to Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  tags:
    - docker
    - permissions

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
  become: true
  tags:
    - docker
    - service
